### ISSUE TITLE
blank messages collapse

### ISSUE THREAD

**Issue by jamietech** [shamiln/textual-whisper#18]
Expected:
![screen shot 2015-01-13 at 5 57 31 pm](https://cloud.githubusercontent.com/assets/948363/5717531/ccc988f8-9b4d-11e4-84f3-747b71a34ba8.png)

Actual:
![screen shot 2015-01-13 at 5 57 53 pm](https://cloud.githubusercontent.com/assets/948363/5717542/3411c44e-9b4e-11e4-940d-a8d8655caf6a.png)

The message in question was simply a space, i.e. ' '.

**Comment by theTeddyBear** [comment]
Confirmed as bug

**Comment by theTeddyBear** [comment]
@jamietech - can you check the latest source, see if it's still happening?
